<?php
/**
 * Adapter over the Freemius SDK's public API — chosen (per product
 * decision) over a custom license-key/update-server build, since
 * Freemius bundles payments, license activation, and auto-updates
 * together, which is exactly what Step 14's brief-mandated "secure
 * licensing, automatic updates" needs without standing up and
 * maintaining that infrastructure independently.
 *
 * What is deliberately NOT in this file: the actual `freemius/` SDK
 * folder and this product's account-specific bootstrap snippet (which
 * embeds a real, Freemius-account-specific plugin ID and public API key,
 * generated by Freemius' own "Start Selling" wizard for this exact
 * product listing). Fabricating that would mean inventing credentials
 * that don't correspond to a real account — the same reasoning as not
 * vendoring a fake copy of Action Scheduler in Step 4. Until that real
 * snippet is dropped into this plugin (see docs/14), every method here
 * fails closed: no SDK present means no license, never "assume licensed."
 *
 * This class only depends on the stable, documented Freemius SDK v2
 * conventions: a generated `{account_slug}_fs()` accessor function, and
 * the instance methods `is_paying()`, `is_trial()`, and
 * `can_use_premium_code()` — all real, public Freemius API, not
 * invented for this file.
 *
 * @package SEODoc
 */

namespace SEODoc\Licensing;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class License_Manager {

	/**
	 * The accessor function name Freemius' wizard generates for this
	 * product. Placeholder until the real integration snippet replaces
	 * it — see the class docblock.
	 */
	const SDK_ACCESSOR_FUNCTION = 'wp_seo_doctor_fs';

	public static function is_valid_license() {
		if ( ! function_exists( self::SDK_ACCESSOR_FUNCTION ) ) {
			return false;
		}

		$fs = call_user_func( self::SDK_ACCESSOR_FUNCTION );

		return $fs->is_paying() || $fs->is_trial() || $fs->can_use_premium_code();
	}

	/**
	 * @return string 'not_configured' | 'free' | 'trial' | 'paid'
	 */
	public static function get_status() {
		if ( ! function_exists( self::SDK_ACCESSOR_FUNCTION ) ) {
			return 'not_configured';
		}

		$fs = call_user_func( self::SDK_ACCESSOR_FUNCTION );

		if ( $fs->is_paying() ) {
			return 'paid';
		}

		if ( $fs->is_trial() ) {
			return 'trial';
		}

		return 'free';
	}
}
